{% set name = "torchmanager-nightly" %}
{% set version = "1.1b3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 8df28e61c619df3ace9a81b2a58037fa2b5602e8c4649dda2e4f6f786f894a2f

build:
  number: 0
  script: "pip install ."

requirements:
  host:
    - pip
    - python >=3.8
    - pytorch
    - tqdm
  run:
    - python >=3.8
    - pytorch
    - tqdm

test:
  imports:
    - torchmanager
    - torchmanager.callbacks
    - torchmanager.data
    - torchmanager.losses
    - torchmanager.metrics
    - torchmanager.train
    - torchmanager_core
    - torchmanager_core.devices
    - torchmanager_core.errors
    - torchmanager_core.view

about:
  home: "https://github.com/kisonho/torchmanager.git"
  license: BSD 2-Clause License
  license_family: BSD
  license_file: LICENSE
  summary: "PyTorch training manager (v1.1 Beta 3)"

extra:
  recipe-maintainers:
    - kisonho
